language: rust

rust:
- stable
- beta
- nightly

os:
  - linux
  - osx

script:
- cd wright && cargo build --release
- cd wright && cargo test
- cd wright && cargo bench

matrix:
  allow_failures:
    - rust: nightly
