language: rust

rust:
- 1.15.0
- 1.16.0
- 1.17.0
- 1.18.0
- 1.19.0
- stable
- beta
- nightly

os:
  - linux
  - osx

script:
- cd wright
- cargo build
- cargo build --release
- cargo test
- cargo bench

matrix:
  allow_failures:
    - rust: nightly
