language: rust

rust:
- 1.15.0
- 1.16.0
- 1.17.0
- 1.18.0
- 1.19.0
- 1.20.0
- stable
- beta
- nightly

os:
  - linux
  - osx


script:
- cd wright
- cargo build
- cargo test

matrix:
  allow_failures:
    - rust: nightly

include:
  # works on Trusty
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"