language: rust

rust:
- stable
- beta
- nightly

os:
  - linux
  - osx

script:
- cd wright
- cargo build
- cargo build --release
- cargo test
- cargo bench

matrix:
  allow_failures:
    - rust: nightly
