language: rust

rust:
- 1.15.0
- 1.16.0
- 1.17.0
- 1.18.0
- 1.19.0
- 1.20.0
- stable
- beta
- nightly

os:
  - linux
  - osx

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install cmake
  - wget https://llvm.org/releases/5.0.0/llvm-5.0.0.src.tar.xz
  - tar xJf llvm-5.0.0.src.tar.xz
  - mkdir -p llvm-5.0.0.src/build
  - cd llvm-5.0.0.src/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/llvm-5.0.0
  - cmake --build . --target install
  -

script:
- cd wright
- LLVM_SYS_50_PREFIX=$HOME/llvm-5.0.0
- cargo build
- cargo test

matrix:
  allow_failures:
    - rust: nightly