# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    - CRATE_NAME=wright

matrix:
  allow_failures:
    - rust: nightly
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=arm-unknown-linux-gnueabi
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=i686-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=i686-unknown-linux-musl
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=mips-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=mips64-unknown-linux-gnuabi64
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=mipsel-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=powerpc-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=powerpc64le-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
      rust:
        - 1.20.0
        - 1.21.0
        - 1.22.0
        - 1.23.0
        - 1.24.0
        - stable
        - beta
        - nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "iN6j+b4J11D+MAQMiljZqeNCAmAHkXVSwsCvLSjx6P279Q/uUG0dHuQKI9f0p+nU/1QP5Am4lWhbjCMuma9ctDtrB2I06YadSCI2pZBsMYrNBciFO+oInFsoIerH2r4fJ0wYljzk2G33VNWzBdPbGF96zz0F/gvz+O5oCNWwE2POWeQCj6+1wdRFOavLfEZ89Pzosg+JRfZWaoLmy8zXQK9iC9Bm9uzl6o10K4sx+08hdwp2z5Lkj0jqHCuSz1jR5QsWdilHTouGF61gNggtY5Z1hcX7tKhI7BFb/0flUH1E/NgSXhYGbw2N5N4PxGHqABcLauXHIaa5gcLBo2ZlcZ3joQDKnt1rmhNO51Brr6MH7xjMxi34ezBRMvsLSH1omOxNXCi3LU5eRne2hn/0oMMZKN+UvnT6bZ+P7J8VRCXR89+pMbS3YgcL4wrFPk8jM3LgHypr3tAM7oz6LFa6FOQkb9fDC2hryvPpRQNQzL967HhVT+WGPS1hFdU/h4MoIgtjekfhItTUit7NdLqrlKsXX7gh6r2Init+tp1ppXDUAkgitwcQVGxhalKa2VqVbX+TROQ0ipLj8lMJL0JVRKIi2josVoVfU/ZNSCOOlazEntL08GZO8VeCehjksbOtJr1nAFhXp7HLZruJtjWlqKIM6crYbI7lfGV1c1RXC9I="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master
