[package]
name = "wright"
description = "The Rust package for the wright language."
licence = "MIT"
version = "0.0.1"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]

[lib]
name = "wright"
crate-type = ["rlib","dylib"]

[dependencies]
regex = "0.2"


[[bin]]
doc = false
name = "wright"
path = "src/wright.rs"