[package]
name = "wright"
description = "The rust package and API for the wright programming language."
license = "MIT"
version = "0.6.1"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]
repository = "https://github.com/Wright-Language-Developers/Wright-lang"
documentation = "https://docs.rs/wright"
readme = "../README.md"
keywords = ["wright", "language", "bytecode", "compiler", "interpreter"]

[lib]
name = "wright"
crate-type = ["rlib", "dylib"]
test = true
doctest = true
doc = true

[dependencies]
regex = "0.2"
colored = "1.6.0"
clap = "~2.31.0"

[[bin]]
doc = false
test = false
name = "wright"

[[bin]]
doc = false
test = false
name = "kittyhawk"

[[bin]]
doc = false
test = false
name = "liftoff"

[[bin]]
doc = false
test = false
name = "airport"

[badges]
travis-ci = {repository = "Wright-Language-Developeres/Wright-lang"}
appveyor = {repository = "Wright-Language-Developers/Wright-lang"}
is-it-maintained-issue-resolution = { repository = "Wright-Language-Developers/Wright-lang" }
is-it-maintained-open-issues = { repository = "Wright-Language-Developers/Wright-lang" }
maintenance = { status = "experimental" }