[package]
name = "wright"
description = "The rust package and API for the wright programming language."
license = "MIT"
version = "0.5.0"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]
repository = "https://github.com/Alfriadox/Wright-lang"
documentation = "https://docs.rs/wright"

[lib]
name = "wright"
crate-type = ["rlib","dylib"]

[dependencies]
regex = "0.2"
ansi_term = "0.10.2"
clap = "~2.30.0"

[[bin]]
doc = false
name = "wright"
path = "src/wright.rs"

[[bin]]
doc = false
name = "kittyhawk"
path = "src/kittyhawk.rs"

[[bin]]
doc = false
name = "liftoff"
path = "src/liftoff.rs"

[badges]
travis-ci = {repository = "Alfriadox/Wright-lang"}