[package]
name = "wright"
description = "The wright programming language interpreter and tooling."
license = "MIT"
version = "0.10.0"
authors = ["Venus Xeon-Blonde <venusflameblonde@gmail.com>"]
repository = "https://github.com/Alfriadox/wright-lang"
documentation = "https://docs.rs/wright"
readme = "../README.md"
keywords = ["wright", "language", "bytecode", "compiler", "interpreter"]
edition.workspace = true
rust-version.workspace = true

[lib]
name = "wright"
test = true
doctest = true
doc = true

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
derive_more = "0.99.17"
unicode-ident = "1.0"
codespan-reporting = "0.11.1"
termcolor = "1.2.0"

# Integers larger than 128 bits
num = "0.4"

# Portable (windows, mac, linux) file locking
fs4 = { version = "0.7.0", features = ["sync"] }

# Memory mapped files. 
memmap2 = "0.9.3"

[[bin]]
name = "wright"
test = false
doc = false
doctest = false

[badges]
maintenance = { status = "actively-developed" }

[dev-dependencies]
rayon = "1.8.0"
