[package]
name = "wright"
description = "The rust package and API for the wright programming language."
license = "MIT"
version = "0.10.0"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]
repository = "https://github.com/Wright-Language-Developers/Wright-lang"
documentation = "https://docs.rs/wright"
readme = "../README.md"
keywords = ["wright", "language", "bytecode", "compiler", "interpreter"]
edition = "2018"

[lib]
name = "wright"
test = true
doctest = true
doc = true

[dependencies]
clap = "3.0.13"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
exitcode = "1"
nom = "7.1.0"
term_size = "0.3.2"
termcolor = "1.1.2"
atty = "0.2.14"

[[bin]]
name = "wright"
test = false
doc = false
doctest = false

[badges]
travis-ci = {repository = "Wright-Language-Developers/Wright-lang"}
appveyor = {repository = "Wright-Language-Developers/Wright-lang"}
is-it-maintained-issue-resolution = { repository = "Wright-Language-Developers/Wright-lang" }
is-it-maintained-open-issues = { repository = "Wright-Language-Developers/Wright-lang" }
maintenance = { status = "actively-developed" }
