[package]
name = "wright"
description = "The wright programming language interpreter."
license = "MIT"
version = "0.10.0"
authors = ["Venus Xeon-Blonde <venusflameblonde@gmail.com>"]
repository = "https://github.com/Alfriadox/wright-lang"
documentation = "https://docs.rs/wright"
readme = "../README.md"
keywords = ["wright", "language", "bytecode", "compiler", "interpreter"]
edition = "2021"

[lib]
name = "wright"
test = true
doctest = true
doc = true

[dependencies]
codespan-reporting = "0.11.1"

[[bin]]
name = "wright"
test = false
doc = false
doctest = false

[badges]
travis-ci = {repository = "Alfriadox/wright-lang"}
appveyor = {repository = "Alfriadox/wright-lang"}
is-it-maintained-issue-resolution = { repository = "Alfriadox/wright-lang" }
is-it-maintained-open-issues = { repository = "Alfriadox/wright-lang" }
maintenance = { status = "actively-developed" }
