[package]
name = "wright"
description = "The Rust package for the wright language."
license = "MIT"
version = "0.0.5"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]
repository = "https://github.com/Alfriadox/Wright-lang"
documentation = "https://alfriadox.github.io/Wright-lang"


[lib]
name = "wright"
crate-type = ["rlib","dylib"]

[dependencies]
regex = "0.2"

[[bin]]
doc = false
name = "wright"
path = "src/wright.rs"

[badges]
travis-ci = { repository = "Alfriadox/Wright-lang" }