[package]
name = "wright"
description = "The Rust package for the wright language."
license = "MIT"
version = "0.4.1"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]
repository = "https://github.com/Alfriadox/Wright-lang"
documentation = "https://docs.rs/wright"


[lib]
name = "wright"
crate-type = ["rlib","dylib"]

[dependencies]
regex = "0.2"
ansi_term = "0.10.2"

[[bin]]
doc = false
name = "wright"
path = "src/wright.rs"

[[bin]]
doc = false
name = "kittyhawk"
path = "src/kittyhawk.rs"


[badges]
travis-ci = {repository = "Alfriadox/Wright-lang"}