[package]
name = "wright"
description = "The rust package and API for the wright programming language."
license = "MIT"
version = "0.8.0"
authors = ["Antonia Calia-Bogan <acaliabogan@gmail.com>"]
repository = "https://github.com/Wright-Language-Developers/Wright-lang"
documentation = "https://docs.rs/wright"
readme = "../README.md"
keywords = ["wright", "language", "bytecode", "compiler", "interpreter"]
edition = "2018"

[lib]
name = "wright"
test = true
doctest = true
doc = true

[dependencies]
#regex = "1"
clap = "~2.33"
codespan = "0.5"
codespan-reporting = "0.5"
#pest = "2.1"
#pest_derive = "2.1"
exitcode = "1"

[[bin]]
name = "wright"
test = false
doc = false
doctest = false

[badges]
travis-ci = {repository = "Wright-Language-Developers/Wright-lang"}
appveyor = {repository = "Wright-Language-Developers/Wright-lang"}
is-it-maintained-issue-resolution = { repository = "Wright-Language-Developers/Wright-lang" }
is-it-maintained-open-issues = { repository = "Wright-Language-Developers/Wright-lang" }
maintenance = { status = "actively-developed" }
