# PACKAGE METADATA
[package]
name = "wright"
description = "The wright programming language compiler and tooling."
license = "MIT"
version = "0.9.0"
authors = ["Venus Xeon-Blonde <venusflameblonde@gmail.com>"]
repository = "https://github.com/vcfxb/wright-lang"
documentation = "https://docs.rs/wright"
readme = "../README.md"
keywords = ["wright", "language", "bytecode", "compiler", "interpreter"]
edition.workspace = true
rust-version.workspace = true

# LIBRARY METADATA
[lib]
name = "wright"
test = true
doctest = true
doc = true

# BINARIES
[[bin]]
name = "wright"
test = false
doc = false
doctest = false

# BENCHMARKS
[[bench]]
name = "lexer"
harness = false

# CRATES.IO BADGES
[badges.maintenance]
status = "actively-developed"

[dependencies]
supports-unicode = "3.0.0"

# DEPENDENCIES: 

# For determining the size of the terminal we're writing to. 
[dependencies.terminal_size]
version = "0.3.0"

# For getting the displayed width of unicode characters. 
[dependencies.unicode-width]
version = "0.1.11"

# Comand-line interface generator
[dependencies.clap]
version = "4"
features = ["derive"]

# Error handling glue code
# [dependencies.anyhow]
# version = "1"

# Derives for various traits
[dependencies.derive_more]
version = "0.99.17"

# Unicode identifier functions
[dependencies.unicode-ident]
version = "1.0"

# Terminal output colors
[dependencies.termcolor]
version = "1.4.1"

# Big Integers
[dependencies.num] 
version = "0.4"

# Portable (windows, mac, linux) file locking
[dependencies.fs4] 
version = "0.7.0"
features = ["sync"]

# Memory mapped files. 
[dependencies.memmap2]
version = "0.9.3"

# Unsafe bindings to LLVM 
# See https://llvm.org/.
[dependencies.llvm-sys]
version = "180"
features = ["force-static"]

# TEST DEPENDENCIES

# Criterion is used for benchmarking. 
[dev-dependencies.criterion] 
version = "0.5.1"

# Rayon is used to do various brute-force tests in parallel
[dev-dependencies.rayon]
version = "1.8.0"
