name: Cargo Check 

on: ["push", "pull_request"]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM package
        run: sudo apt-get install llvm-17-dev
      - name: Check rust code
        run: cargo check 
        working-directory: ${{env.working-directory}}
