name: Clippy 

on: ["push", "pull_request"]

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM package
        run: sudo apt-get install llvm-17-dev
      - name: Run Clippy
        run: cargo clippy -- --deny clippy::all --deny warnings
        working-directory: ${{env.working-directory}}
