name: Cargo Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Check rust code
        run: cargo check 
        working-directory: ${{env.working-directory}}
