name: Cargo Check 

on: ["push", "pull_request"]

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM package
        run: |
          deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
          deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
          sudo apt-get install llvm-17-dev
      - name: Check rust code
        run: cargo check 
        working-directory: ${{env.working-directory}}
