name: Cargo Check 

on: ["push", "pull_request"]

jobs:
  check:
    strategy: 
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17"
      - name: Check rust code
        run: cargo check 
        working-directory: ${{env.working-directory}}
