# Combined cargo check with LLVM installation for the three major platforms.

name: Cargo Check
on: ["push", "pull_request"]

# Cancel in-progress runs for previous commits if there are any that haven't completed yet.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include: 
          - os: windows-latest
            llvm-install-dir: llvm-18-install

    runs-on: ${{ matrix.os }}
    
    # Cached checkout of the LLVM source code, excluding CLANG and any other tools we don't need. 
    steps:
      - name: Checkout Wright source
        uses: actions/checkout@v4
      
      # Use stable Rust toolchain 
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - id: cache-windows-llvm-install
        name: Cache Windows LLVM 18 installation
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/cache@v4
        with:
          path: ./${{ matrix.llvm-install-dir }}
          key: windows-llvm-8-1-1-install

      - name: Install LLVM (Windows Only)
        if: ${{ matrix.os == 'windows-latest' && steps.cache-windows-llvm-install.outputs.cache-hit != 'true' }}
        run: cargo run --release --bin install-llvm-windows -- ../${{ matrix.llvm-install-dir }}
        working-directory: ./ci

      - name: Install LLVM (Ubuntu Only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # See: https://apt.llvm.org/
        # Last line: https://gitlab.com/taricorp/llvm-sys.rs/-/issues/13
        # Add sudo apt update to make sure stuff resolves correctly
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt install libpolly-18-dev libz-dev

      - name: Install LLVM 18 (Mac only)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install llvm
      
      - name: Get the LLVM version
        run: |
          ${{ matrix.os == 'windows-latest' && format('./{0}/bin/llvm-config.exe', matrix.llvm-install-dir)  || 'llvm-config'}} --version
        continue-on-error: true
      
      # Cargo check
      - name: Run cargo check
        run: cargo check
        env:
          LLVM_SYS_180_PREFIX: ${{ matrix.os == 'windows-latest' && format('./{0}/', matrix.llvm-install-dir) || '' }}
