name: Cargo Check 

on: ["push", "pull_request"]

jobs:
  check:
    strategy: 
      matrix:
        include: 
          - os: windows-latest
            llvm-dir: C:/LLVM
          - os: ubuntu-latest
            llvm-dir: ./llvm
          # macos does not support LLVM 17.

    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Cache LLVM installation
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ${{ matrix.llvm_dir }}
          key: llvm-17
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17"
          directory: ${{ matrix.llvm_dir }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Check LLVM version
        run: llvm-config --version
      - name: Check rust code
        run: cargo check
        working-directory: ${{env.working-directory}}
