name: Clippy 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy -- --deny clippy::all --deny warnings
        working-directory: ${{env.working-directory}}
