name: Cargo Test 

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM package
        run: sudo apt-get install llvm-17-dev
      - name: Run tests
        run: cargo test
        working-directory: ${{env.working-directory}}
