name: Cargo Check (Windows)

on: ["push", "pull_request"]

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache LLVM git source tree
        id: cache-llvm-source
        uses: actions/cache@v3
        with:
          path: llvm-project
          key: llvm-17-src
      
      - name: Pull LLVM 17.0.6 source.
        if: steps.cache-llvm-source.outputs.cache-hit != 'true'
        run: git clone --depth 1 --config core.autocrlf=false --branch llvmorg-17.0.6 https://github.com/llvm/llvm-project.git

      - name: Build LLVM
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          mkdir build
          cd build

          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:\LLVM" ../llvm-project/llvm
          cmake --build . --config Release

          if not exist C:\LLVM mkdir C:\LLVM
          cmake --build . --target install --config Release
        
      - name: Check LLVM version
        run: C:\LLVM\bin\llvm-config.exe --version
      # - name: Check rust code
      #   run: cargo check
          
