# Combined cargo check with LLVM installation for the three major platforms.

name: Cargo Check
on: ["push", "pull_request"]

# Cancel in-progress runs for previous commits if there are any that haven't completed yet.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include: 
          - os: windows-latest
            llvm-install-dir: ./llvm-18-install
          - os: macos-latest
            llvm-install-dir: /usr/local/opt/llvm

    runs-on: ${{ matrix.os }}
    
    # Cached checkout of the LLVM source code, excluding CLANG and any other tools we don't need. 
    steps:
      - name: Checkout Wright source
        uses: actions/checkout@v4
      
      # Use stable Rust toolchain 
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install LLVM (Windows Only)
        if: ${{ matrix.os == 'windows-latest' && steps.cache-windows-llvm-install.outputs.cache-hit != 'true' }}
        run: cargo run --release --bin install-llvm-windows -- ../${{ matrix.llvm-install-dir }}
        working-directory: ./ci

      - name: Install LLVM (Ubuntu Only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # See: https://apt.llvm.org/
        # Last line: https://gitlab.com/taricorp/llvm-sys.rs/-/issues/13
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt install libpolly-18-dev libz-dev

      - name: Install LLVM 18 (Mac Only)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install llvm@18
      
      - name: Get the LLVM version (Windows Only)
        if: ${{ matrix.os == 'windows-latest' }}
        run: ${{ format('{0}/bin/llvm-config.exe', matrix.llvm-install-dir) }} --version
        continue-on-error: true

      - name: Get the LLVM version (Mac Only)
        if: ${{ matrix.os == 'macos-latest' }}
        run: ${{ matrix.llvm-install-dir }}/bin/llvm-config --version
        continue-on-error: true
        
      - name: Get the LLVM version (Ubuntu Only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: llvm-config --version
        continue-on-error: true

      - name: Run cargo check (Mac & Windows)
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: | 
          echo $LLVM_SYS_180_PREFIX
          cargo check
        env:
          LLVM_SYS_180_PREFIX: ${{ matrix.llvm-install-dir }}      
      
      - name: Run cargo check (Ubuntu Only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo check
