name: Cargo Test 

on: ["push", "pull_request"]

# Cancel in-progress runs for previous commits if there are any that haven't completed yet.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # Call reusable LLVM-setup workflow
    uses: ./.github/workflows/setup-llvm.yml

    steps:
      - uses: actions/checkout@v4
      
      - name: Run tests
        run: cargo test
