name: Release

on:
    

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        # See: https://apt.llvm.org/
        # Last line: https://gitlab.com/taricorp/llvm-sys.rs/-/issues/13
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
          sudo apt install libpolly-17-dev libz-dev
      - name: Check rust code
        run: cargo check 
        working-directory: ${{env.working-directory}}
