name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working-directory}}
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wright
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
        working-directory: ${{env.working-directory}}
